services:
   external-fhir:
      build: .
      image: fhir-data-communication:1.0
      container_name: fhir-data-communication
      ports:
         - "7002:7002"
      command: /bin/bash -c "java -jar /app/target/fhir.data.communication-0.0.1-SNAPSHOT.jar"
